version: '3.7'
services:
  server:
    image: iputus/server:develop-1.0
    build: 
      context: ./server
      target: prd
    ports:
      - 50051:50051
    environment:
      REDIS_URL: redis
  redis:
    image: redis
    ports:
      - 6379:6379
  envoy:
    image: iputus/envoy:develop-1.0
    ports:
      - "8080:8080"
      - "9901:9901"
