version: '3.7'
services:
  server:
    image: iputus/server:develop-1.1
    ports:
      - 50051:50051
    environment:
      REDIS_URL: redis
      TZ: Asia/Tokyo
    tty: true
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Tokyo
  envoy:
    image: iputus/envoy:develop-1.1
    ports:
      - "80:8080"
      - "9901:9901"
    environment:
      TZ: Asia/Tokyo
