version: '3.7'
services:
  server:
    build: ./server
    ports:
      - 50051:50051
    environment:
      REDIS_URL: redis
  redis:
    image: redis
    ports:
      - 6379:6379
  envoy:
    build: ./envoy
    ports:
      - "8080:8080"
      - "9901:9901"

