version: '3.7'
services:
  server:
    build: ./server
    ports:
      - 50051:50051
    volumes:
      - ./server/:/go/src/app
    environment:
      REDIS_URL: redis
      TZ: Asia/Tokyo
      DIC_PATH: /word.txt
      FIREBASE_CREDENTIALS: /go/src/app/serviceAccount.json
      SERVER_VERSION: 1.4.0
      LOG_LEVEL: 'DEBUG'
    tty: true
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Tokyo
  envoy:
    build: ./envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    environment:
      TZ: Asia/Tokyo

