version: '3.7'
services:
  server:
    build: 
      context: ./server
      target: dev
    ports:
      - 50051:50051
    volumes:
      - ./server/:/go/src/app
    environment:
      REDIS_URL: redis
  redis:
    image: redis
    ports:
      - 6379:6379
  envoy:
    build: ./envoy
    ports:
      - "8080:8080"
      - "9901:9901"

