// Code generated by protoc-gen-go. DO NOT EDIT.
// source: word_war.proto

package word_war

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayRequest) Reset()         { *m = SayRequest{} }
func (m *SayRequest) String() string { return proto.CompactTextString(m) }
func (*SayRequest) ProtoMessage()    {}
func (*SayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{0}
}

func (m *SayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayRequest.Unmarshal(m, b)
}
func (m *SayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayRequest.Marshal(b, m, deterministic)
}
func (m *SayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayRequest.Merge(m, src)
}
func (m *SayRequest) XXX_Size() int {
	return xxx_messageInfo_SayRequest.Size(m)
}
func (m *SayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayRequest proto.InternalMessageInfo

func (m *SayRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SayRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SayResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayResponse) Reset()         { *m = SayResponse{} }
func (m *SayResponse) String() string { return proto.CompactTextString(m) }
func (*SayResponse) ProtoMessage()    {}
func (*SayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{1}
}

func (m *SayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResponse.Unmarshal(m, b)
}
func (m *SayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResponse.Marshal(b, m, deterministic)
}
func (m *SayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResponse.Merge(m, src)
}
func (m *SayResponse) XXX_Size() int {
	return xxx_messageInfo_SayResponse.Size(m)
}
func (m *SayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayResponse proto.InternalMessageInfo

func (m *SayResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SayResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GameRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameRequest) Reset()         { *m = GameRequest{} }
func (m *GameRequest) String() string { return proto.CompactTextString(m) }
func (*GameRequest) ProtoMessage()    {}
func (*GameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{2}
}

func (m *GameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRequest.Unmarshal(m, b)
}
func (m *GameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRequest.Marshal(b, m, deterministic)
}
func (m *GameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRequest.Merge(m, src)
}
func (m *GameRequest) XXX_Size() int {
	return xxx_messageInfo_GameRequest.Size(m)
}
func (m *GameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameRequest proto.InternalMessageInfo

func (m *GameRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GameResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResponse) Reset()         { *m = GameResponse{} }
func (m *GameResponse) String() string { return proto.CompactTextString(m) }
func (*GameResponse) ProtoMessage()    {}
func (*GameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{3}
}

func (m *GameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResponse.Unmarshal(m, b)
}
func (m *GameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResponse.Marshal(b, m, deterministic)
}
func (m *GameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResponse.Merge(m, src)
}
func (m *GameResponse) XXX_Size() int {
	return xxx_messageInfo_GameResponse.Size(m)
}
func (m *GameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameResponse proto.InternalMessageInfo

func (m *GameResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResultRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultRequest) Reset()         { *m = ResultRequest{} }
func (m *ResultRequest) String() string { return proto.CompactTextString(m) }
func (*ResultRequest) ProtoMessage()    {}
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{4}
}

func (m *ResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultRequest.Unmarshal(m, b)
}
func (m *ResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultRequest.Marshal(b, m, deterministic)
}
func (m *ResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultRequest.Merge(m, src)
}
func (m *ResultRequest) XXX_Size() int {
	return xxx_messageInfo_ResultRequest.Size(m)
}
func (m *ResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResultRequest proto.InternalMessageInfo

func (m *ResultRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ResultResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Score                string   `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultResponse) Reset()         { *m = ResultResponse{} }
func (m *ResultResponse) String() string { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()    {}
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{5}
}

func (m *ResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultResponse.Unmarshal(m, b)
}
func (m *ResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultResponse.Marshal(b, m, deterministic)
}
func (m *ResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultResponse.Merge(m, src)
}
func (m *ResultResponse) XXX_Size() int {
	return xxx_messageInfo_ResultResponse.Size(m)
}
func (m *ResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResultResponse proto.InternalMessageInfo

func (m *ResultResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ResultResponse) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func init() {
	proto.RegisterType((*SayRequest)(nil), "word_war.SayRequest")
	proto.RegisterType((*SayResponse)(nil), "word_war.SayResponse")
	proto.RegisterType((*GameRequest)(nil), "word_war.GameRequest")
	proto.RegisterType((*GameResponse)(nil), "word_war.GameResponse")
	proto.RegisterType((*ResultRequest)(nil), "word_war.ResultRequest")
	proto.RegisterType((*ResultResponse)(nil), "word_war.ResultResponse")
}

func init() { proto.RegisterFile("word_war.proto", fileDescriptor_9e6bc0bf977bdab9) }

var fileDescriptor_9e6bc0bf977bdab9 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xcf, 0x2f, 0x4a,
	0x89, 0x2f, 0x4f, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xec,
	0xb8, 0xb8, 0x82, 0x13, 0x2b, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xc4, 0xb8, 0xd8,
	0x4a, 0x8b, 0x53, 0x8b, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x21,
	0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0xb0, 0x04, 0x8c, 0xab,
	0x64, 0xcf, 0xc5, 0x0d, 0xd6, 0x5f, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x4a, 0x86, 0x01, 0xaa, 0x5c,
	0xdc, 0xee, 0x89, 0xb9, 0xa9, 0x04, 0x5c, 0xa0, 0xe4, 0xc0, 0xc5, 0x03, 0x51, 0x46, 0xb6, 0x45,
	0xea, 0x5c, 0xbc, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x84, 0xac, 0xb2, 0xe3, 0xe2, 0x83, 0x29,
	0x24, 0x60, 0x99, 0x08, 0x17, 0x6b, 0x71, 0x72, 0x7e, 0x11, 0xcc, 0x2a, 0x08, 0xc7, 0x68, 0x27,
	0x23, 0x17, 0x7b, 0x78, 0x7e, 0x51, 0x4a, 0x78, 0x62, 0x91, 0x90, 0x09, 0x17, 0x73, 0x70, 0x62,
	0xa5, 0x90, 0x88, 0x1e, 0x3c, 0x02, 0x10, 0xa1, 0x2d, 0x25, 0x8a, 0x26, 0x0a, 0xb1, 0x4d, 0x89,
	0x41, 0xc8, 0x92, 0x8b, 0x05, 0xe4, 0x59, 0x21, 0x24, 0x05, 0x48, 0x61, 0x24, 0x25, 0x86, 0x2e,
	0x0c, 0xd3, 0x68, 0xc0, 0x28, 0x64, 0xcb, 0xc5, 0x06, 0x71, 0xbc, 0x90, 0x38, 0x42, 0x15, 0x8a,
	0xbf, 0xa5, 0x24, 0x30, 0x25, 0x60, 0x06, 0x24, 0xb1, 0x81, 0xd3, 0x87, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x69, 0xa3, 0x91, 0xcf, 0x31, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WordWarClient is the client API for WordWar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WordWarClient interface {
	Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayResponse, error)
	Game(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (WordWar_GameClient, error)
	Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type wordWarClient struct {
	cc *grpc.ClientConn
}

func NewWordWarClient(cc *grpc.ClientConn) WordWarClient {
	return &wordWarClient{cc}
}

func (c *wordWarClient) Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayResponse, error) {
	out := new(SayResponse)
	err := c.cc.Invoke(ctx, "/word_war.WordWar/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordWarClient) Game(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (WordWar_GameClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WordWar_serviceDesc.Streams[0], "/word_war.WordWar/Game", opts...)
	if err != nil {
		return nil, err
	}
	x := &wordWarGameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WordWar_GameClient interface {
	Recv() (*GameResponse, error)
	grpc.ClientStream
}

type wordWarGameClient struct {
	grpc.ClientStream
}

func (x *wordWarGameClient) Recv() (*GameResponse, error) {
	m := new(GameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wordWarClient) Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/word_war.WordWar/Result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordWarServer is the server API for WordWar service.
type WordWarServer interface {
	Say(context.Context, *SayRequest) (*SayResponse, error)
	Game(*GameRequest, WordWar_GameServer) error
	Result(context.Context, *ResultRequest) (*ResultResponse, error)
}

// UnimplementedWordWarServer can be embedded to have forward compatible implementations.
type UnimplementedWordWarServer struct {
}

func (*UnimplementedWordWarServer) Say(ctx context.Context, req *SayRequest) (*SayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}
func (*UnimplementedWordWarServer) Game(req *GameRequest, srv WordWar_GameServer) error {
	return status.Errorf(codes.Unimplemented, "method Game not implemented")
}
func (*UnimplementedWordWarServer) Result(ctx context.Context, req *ResultRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}

func RegisterWordWarServer(s *grpc.Server, srv WordWarServer) {
	s.RegisterService(&_WordWar_serviceDesc, srv)
}

func _WordWar_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordWarServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/word_war.WordWar/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordWarServer).Say(ctx, req.(*SayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordWar_Game_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WordWarServer).Game(m, &wordWarGameServer{stream})
}

type WordWar_GameServer interface {
	Send(*GameResponse) error
	grpc.ServerStream
}

type wordWarGameServer struct {
	grpc.ServerStream
}

func (x *wordWarGameServer) Send(m *GameResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WordWar_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordWarServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/word_war.WordWar/Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordWarServer).Result(ctx, req.(*ResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WordWar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "word_war.WordWar",
	HandlerType: (*WordWarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _WordWar_Say_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _WordWar_Result_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Game",
			Handler:       _WordWar_Game_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "word_war.proto",
}
