// Code generated by protoc-gen-go. DO NOT EDIT.
// source: word_war.proto

package word_war

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayRequest) Reset()         { *m = SayRequest{} }
func (m *SayRequest) String() string { return proto.CompactTextString(m) }
func (*SayRequest) ProtoMessage()    {}
func (*SayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{0}
}

func (m *SayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayRequest.Unmarshal(m, b)
}
func (m *SayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayRequest.Marshal(b, m, deterministic)
}
func (m *SayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayRequest.Merge(m, src)
}
func (m *SayRequest) XXX_Size() int {
	return xxx_messageInfo_SayRequest.Size(m)
}
func (m *SayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayRequest proto.InternalMessageInfo

func (m *SayRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SayRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SayRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type SayResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Valid                bool     `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayResponse) Reset()         { *m = SayResponse{} }
func (m *SayResponse) String() string { return proto.CompactTextString(m) }
func (*SayResponse) ProtoMessage()    {}
func (*SayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{1}
}

func (m *SayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResponse.Unmarshal(m, b)
}
func (m *SayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResponse.Marshal(b, m, deterministic)
}
func (m *SayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResponse.Merge(m, src)
}
func (m *SayResponse) XXX_Size() int {
	return xxx_messageInfo_SayResponse.Size(m)
}
func (m *SayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayResponse proto.InternalMessageInfo

func (m *SayResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SayResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SayResponse) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *SayResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type MatchingRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchingRequest) Reset()         { *m = MatchingRequest{} }
func (m *MatchingRequest) String() string { return proto.CompactTextString(m) }
func (*MatchingRequest) ProtoMessage()    {}
func (*MatchingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{2}
}

func (m *MatchingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchingRequest.Unmarshal(m, b)
}
func (m *MatchingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchingRequest.Marshal(b, m, deterministic)
}
func (m *MatchingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchingRequest.Merge(m, src)
}
func (m *MatchingRequest) XXX_Size() int {
	return xxx_messageInfo_MatchingRequest.Size(m)
}
func (m *MatchingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MatchingRequest proto.InternalMessageInfo

func (m *MatchingRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// TODO: ここにへやの情報がはいる
type MatchingResponse struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchingResponse) Reset()         { *m = MatchingResponse{} }
func (m *MatchingResponse) String() string { return proto.CompactTextString(m) }
func (*MatchingResponse) ProtoMessage()    {}
func (*MatchingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{3}
}

func (m *MatchingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchingResponse.Unmarshal(m, b)
}
func (m *MatchingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchingResponse.Marshal(b, m, deterministic)
}
func (m *MatchingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchingResponse.Merge(m, src)
}
func (m *MatchingResponse) XXX_Size() int {
	return xxx_messageInfo_MatchingResponse.Size(m)
}
func (m *MatchingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MatchingResponse proto.InternalMessageInfo

func (m *MatchingResponse) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type GameRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameRequest) Reset()         { *m = GameRequest{} }
func (m *GameRequest) String() string { return proto.CompactTextString(m) }
func (*GameRequest) ProtoMessage()    {}
func (*GameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{4}
}

func (m *GameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRequest.Unmarshal(m, b)
}
func (m *GameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRequest.Marshal(b, m, deterministic)
}
func (m *GameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRequest.Merge(m, src)
}
func (m *GameRequest) XXX_Size() int {
	return xxx_messageInfo_GameRequest.Size(m)
}
func (m *GameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameRequest proto.InternalMessageInfo

func (m *GameRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GameRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type GameResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResponse) Reset()         { *m = GameResponse{} }
func (m *GameResponse) String() string { return proto.CompactTextString(m) }
func (*GameResponse) ProtoMessage()    {}
func (*GameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{5}
}

func (m *GameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResponse.Unmarshal(m, b)
}
func (m *GameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResponse.Marshal(b, m, deterministic)
}
func (m *GameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResponse.Merge(m, src)
}
func (m *GameResponse) XXX_Size() int {
	return xxx_messageInfo_GameResponse.Size(m)
}
func (m *GameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameResponse proto.InternalMessageInfo

func (m *GameResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GameResponse) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type ResultRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultRequest) Reset()         { *m = ResultRequest{} }
func (m *ResultRequest) String() string { return proto.CompactTextString(m) }
func (*ResultRequest) ProtoMessage()    {}
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{6}
}

func (m *ResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultRequest.Unmarshal(m, b)
}
func (m *ResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultRequest.Marshal(b, m, deterministic)
}
func (m *ResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultRequest.Merge(m, src)
}
func (m *ResultRequest) XXX_Size() int {
	return xxx_messageInfo_ResultRequest.Size(m)
}
func (m *ResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResultRequest proto.InternalMessageInfo

func (m *ResultRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ResultRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type ResultResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Score                string   `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultResponse) Reset()         { *m = ResultResponse{} }
func (m *ResultResponse) String() string { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()    {}
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e6bc0bf977bdab9, []int{7}
}

func (m *ResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultResponse.Unmarshal(m, b)
}
func (m *ResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultResponse.Marshal(b, m, deterministic)
}
func (m *ResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultResponse.Merge(m, src)
}
func (m *ResultResponse) XXX_Size() int {
	return xxx_messageInfo_ResultResponse.Size(m)
}
func (m *ResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResultResponse proto.InternalMessageInfo

func (m *ResultResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ResultResponse) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *ResultResponse) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func init() {
	proto.RegisterType((*SayRequest)(nil), "word_war.SayRequest")
	proto.RegisterType((*SayResponse)(nil), "word_war.SayResponse")
	proto.RegisterType((*MatchingRequest)(nil), "word_war.MatchingRequest")
	proto.RegisterType((*MatchingResponse)(nil), "word_war.MatchingResponse")
	proto.RegisterType((*GameRequest)(nil), "word_war.GameRequest")
	proto.RegisterType((*GameResponse)(nil), "word_war.GameResponse")
	proto.RegisterType((*ResultRequest)(nil), "word_war.ResultRequest")
	proto.RegisterType((*ResultResponse)(nil), "word_war.ResultResponse")
}

func init() { proto.RegisterFile("word_war.proto", fileDescriptor_9e6bc0bf977bdab9) }

var fileDescriptor_9e6bc0bf977bdab9 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcf, 0x4f, 0xc2, 0x30,
	0x18, 0xb5, 0xfc, 0xf6, 0x43, 0xd1, 0x7c, 0x41, 0xac, 0x3b, 0x91, 0x9e, 0xd0, 0x03, 0x31, 0xea,
	0xc5, 0x03, 0xf1, 0xe0, 0xc1, 0x70, 0xf0, 0x32, 0x12, 0xf0, 0x66, 0x2a, 0x6b, 0x90, 0x84, 0x51,
	0x6c, 0x37, 0x09, 0xff, 0xbc, 0x31, 0xac, 0x94, 0xb2, 0xa9, 0x59, 0x62, 0x38, 0xbe, 0x7e, 0xef,
	0xbd, 0xbd, 0xbe, 0x7e, 0x83, 0xc6, 0x52, 0xaa, 0xe0, 0x75, 0xc9, 0x55, 0x77, 0xa1, 0x64, 0x24,
	0xb1, 0x66, 0x31, 0x1b, 0x02, 0x0c, 0xf8, 0xca, 0x17, 0x1f, 0xb1, 0xd0, 0x11, 0xb6, 0xa0, 0x12,
	0x6b, 0xa1, 0xfa, 0x01, 0x25, 0x6d, 0xd2, 0x39, 0xf4, 0x37, 0x08, 0x29, 0x54, 0x43, 0xa1, 0x35,
	0x9f, 0x08, 0x5a, 0x48, 0x06, 0x16, 0xae, 0x15, 0x4a, 0xca, 0xb0, 0x1f, 0xd0, 0xa2, 0x51, 0x18,
	0xc4, 0x42, 0xa8, 0x27, 0xbe, 0x7a, 0x21, 0xe7, 0x5a, 0xec, 0xcf, 0x18, 0x9b, 0x50, 0xfe, 0xe4,
	0xb3, 0x69, 0x40, 0x4b, 0x6d, 0xd2, 0xa9, 0xf9, 0x06, 0xb0, 0x4b, 0x38, 0x79, 0xe6, 0xd1, 0xf8,
	0x7d, 0x3a, 0x9f, 0xe4, 0xdc, 0x85, 0x5d, 0xc1, 0xa9, 0xa3, 0xba, 0x78, 0x9b, 0x8f, 0x91, 0xd4,
	0x2d, 0x7a, 0x50, 0x7f, 0xe2, 0xa1, 0xc8, 0xab, 0xc7, 0xc9, 0x0b, 0x29, 0xf9, 0x0b, 0x1c, 0x19,
	0xf9, 0xbe, 0x5b, 0x60, 0x0f, 0x70, 0xec, 0x0b, 0x1d, 0xcf, 0xa2, 0xff, 0x46, 0x1b, 0x42, 0xc3,
	0x1a, 0xe4, 0x84, 0x6b, 0x42, 0x59, 0x8f, 0xa5, 0xb2, 0xd1, 0x0c, 0xf8, 0x2b, 0xd8, 0xcd, 0x17,
	0x81, 0xea, 0x48, 0xaa, 0x60, 0xc4, 0x15, 0x3e, 0x42, 0xcd, 0x36, 0x8d, 0x17, 0xdd, 0xed, 0x0a,
	0x66, 0x1e, 0xca, 0xf3, 0x7e, 0x1b, 0x99, 0x50, 0xec, 0x00, 0xef, 0xa0, 0x38, 0xe0, 0x2b, 0x6c,
	0x3a, 0x92, 0xdb, 0x57, 0xef, 0x2c, 0x73, 0xba, 0x55, 0xdd, 0x43, 0x69, 0xdd, 0x3c, 0xee, 0x10,
	0x76, 0x1e, 0xd2, 0x6b, 0x65, 0x8f, 0xad, 0xf0, 0x9a, 0x60, 0x0f, 0x2a, 0xa6, 0x19, 0x3c, 0x77,
	0xac, 0x54, 0xd9, 0x1e, 0xfd, 0x39, 0xb0, 0x06, 0x6f, 0x95, 0xe4, 0x0f, 0xbb, 0xfd, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xd0, 0x79, 0x17, 0xd2, 0x73, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WordWarClient is the client API for WordWar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WordWarClient interface {
	Matching(ctx context.Context, in *MatchingRequest, opts ...grpc.CallOption) (*MatchingResponse, error)
	Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayResponse, error)
	Game(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (WordWar_GameClient, error)
	Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type wordWarClient struct {
	cc *grpc.ClientConn
}

func NewWordWarClient(cc *grpc.ClientConn) WordWarClient {
	return &wordWarClient{cc}
}

func (c *wordWarClient) Matching(ctx context.Context, in *MatchingRequest, opts ...grpc.CallOption) (*MatchingResponse, error) {
	out := new(MatchingResponse)
	err := c.cc.Invoke(ctx, "/word_war.WordWar/Matching", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordWarClient) Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayResponse, error) {
	out := new(SayResponse)
	err := c.cc.Invoke(ctx, "/word_war.WordWar/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordWarClient) Game(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (WordWar_GameClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WordWar_serviceDesc.Streams[0], "/word_war.WordWar/Game", opts...)
	if err != nil {
		return nil, err
	}
	x := &wordWarGameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WordWar_GameClient interface {
	Recv() (*GameResponse, error)
	grpc.ClientStream
}

type wordWarGameClient struct {
	grpc.ClientStream
}

func (x *wordWarGameClient) Recv() (*GameResponse, error) {
	m := new(GameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wordWarClient) Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/word_war.WordWar/Result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordWarServer is the server API for WordWar service.
type WordWarServer interface {
	Matching(context.Context, *MatchingRequest) (*MatchingResponse, error)
	Say(context.Context, *SayRequest) (*SayResponse, error)
	Game(*GameRequest, WordWar_GameServer) error
	Result(context.Context, *ResultRequest) (*ResultResponse, error)
}

// UnimplementedWordWarServer can be embedded to have forward compatible implementations.
type UnimplementedWordWarServer struct {
}

func (*UnimplementedWordWarServer) Matching(ctx context.Context, req *MatchingRequest) (*MatchingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Matching not implemented")
}
func (*UnimplementedWordWarServer) Say(ctx context.Context, req *SayRequest) (*SayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}
func (*UnimplementedWordWarServer) Game(req *GameRequest, srv WordWar_GameServer) error {
	return status.Errorf(codes.Unimplemented, "method Game not implemented")
}
func (*UnimplementedWordWarServer) Result(ctx context.Context, req *ResultRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}

func RegisterWordWarServer(s *grpc.Server, srv WordWarServer) {
	s.RegisterService(&_WordWar_serviceDesc, srv)
}

func _WordWar_Matching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordWarServer).Matching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/word_war.WordWar/Matching",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordWarServer).Matching(ctx, req.(*MatchingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordWar_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordWarServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/word_war.WordWar/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordWarServer).Say(ctx, req.(*SayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordWar_Game_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WordWarServer).Game(m, &wordWarGameServer{stream})
}

type WordWar_GameServer interface {
	Send(*GameResponse) error
	grpc.ServerStream
}

type wordWarGameServer struct {
	grpc.ServerStream
}

func (x *wordWarGameServer) Send(m *GameResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WordWar_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordWarServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/word_war.WordWar/Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordWarServer).Result(ctx, req.(*ResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WordWar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "word_war.WordWar",
	HandlerType: (*WordWarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Matching",
			Handler:    _WordWar_Matching_Handler,
		},
		{
			MethodName: "Say",
			Handler:    _WordWar_Say_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _WordWar_Result_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Game",
			Handler:       _WordWar_Game_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "word_war.proto",
}
