# FROM iputus/go-mecab-neologd
FROM iputus/kagome-neologd-dic AS csv


FROM python:latest AS dic

COPY --from=csv /go/src/github.com/ikawaha/kagome/cmd/_dictool/mecab-user-dict-seed.20191212.csv mecab.csv

RUN curl -sOL https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz \
    && tar -zxvf xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz \
    && mv xsv /usr/local/bin

COPY scripts/make_words.py .

RUN pip install jaconv && python make_words.py mecab.csv /word.txt


FROM golang:1.14.2-alpine

WORKDIR /go/src/app

ENV GO111MODULE on
COPY go.mod go.sum ./
RUN go mod download

COPY . .

COPY --from=dic /word.txt /

RUN go get github.com/cespare/reflex

# ENTRYPOINT "reflex --help"
ENTRYPOINT /go/bin/reflex -r '(\.go$|go\.mod)' -s go run /go/src/app/main.go
