name: Server Docker Build

on:
  push:
    branches:
      - 'develop/**'
      - 'chore/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish server image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: iputus/server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: server
        tag: ${{ secrets.DOCKER_USERNAME }}/server:github-sha-${{ github.sha }}

    - name: Publish server image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: iputus/envoy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: envoy
        tag: ${{ secrets.DOCKER_USERNAME }}/envoy:github-sha-${{ github.sha }}
