name: Server Docker Build

on:
  push:
    branches:
      - 'develop/1.0'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish server image
      id: publish-server-image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: iputus/server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: server
        snapshot: true

    - name: Publish envoy image
      id: publish-envoy-image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: iputus/envoy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: envoy
        snapshot: true

    - name: echo outputs
      id: echo
      run: |
        echo ${{ steps.publish-server-image.outputs.snapshot-tag }}
        echo ${{ steps.publish-envoy-image.outputs.snapshot-tag }}
