name: Server Test

on:
  push:
    branches: 
      - 'master'
      - 'develop/*'
      - 'feature/*'
      - 'chore/*'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: go test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: Run tests
      run: |
        cd server
        go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
        bash <(curl -s https://codecov.io/bash)
